# Read the data frame 
# priovide the data
# provide the column names
# change the index 
# Add the new column
# modify the existing column
# Drop the column
# sxis inplace 
# you need to create a new column
# Drop the old column



**Step-8**

**drop the row**

- drop the column and drop the rows both are similar only 

- the only diffrent is axis

  - axis=0 represents rows

  - by default axis=0 available 

  - Which means if we provide any value , it will represent rows only 



In [ ]:
# Dataframe bane: 

In [6]:
import pandas as pd
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df2['Number']=l1
df2['Square']=l2
df2['Cube']=l3
df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [8]:
df2.drop(4)

# if we run this we will get error
# by default axis=0 which represents about rows
# by 'Number' is a column
# if you want to drop row, the provide the row index

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [4]:
# Multiple rows
#Multiple columns keep always in a list
df2.drop([4,8])

Number  Aquare  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [9]:
df2.columns[[0,1]] # previous data

Index(['Number', 'Square'], dtype='object')

In [12]:
df2.drop([0,1],axis=1)
#[0,1]index
# axis=columns
#error

KeyError: '[0, 1] not found in axis'

**Step-9**

How to select the column

In [16]:
df2.columns[1]

'Square'

In [18]:
df2['Square']

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: Square, dtype: int64

In [20]:
df2[['Square']]
# DataFrame 

Square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

In [21]:
type(df2['Number'])

pandas.core.series.Series

In [22]:
type(df2[['Number']])

pandas.core.frame.DataFrame

In [23]:
df2.Number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

- df2['Number']:Series type

- df2[['Number']]:Dataframe type

- df2.Number:Series type

In [24]:
cols=['Number','Square']
df2[cols]

Number  Square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [25]:
df2['Number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- all values comes in an array

- array means it is a list of element only represent using numpy package

- generally elements present in 4 ways

  - List: Basic representations

  - Numpy array: Array with Numpy package

  - Tensors: Tensorflow package

  - Torch: pytorch package

In [26]:
list1=[1,2,3,4,]
list1

[1, 2, 3, 4]

In [27]:
import numpy as np
np.array(list1) # array add

array([1, 2, 3, 4])

In [ ]:
# tensor([1,2,3,4])

In [28]:
list1=[1,2,3,4,]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [29]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [ ]:
# 3 day every day one numpy
# A new package in the market : numpy
# you know python 

In [30]:
df2['Number'].values
# imagine we worked on an Ml problem
#we got some series of values
# with that series of values also we can create a dataframe

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [31]:
df2['NUMBER']=df2['Number'].values
df2

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

**step no10**


**How to save the dataframe**

- dataframe  we can save in two formats
- csv: comma seprated value
- xlsx: excel format

- in order to save any data
  - where you went to save: directory name

  - what is the name of the file for storing

  - what is the extension
- we already seen seem in fie handling session


In [ ]:
# case1: saving file at same location where this python file
# import os
#os.getcwd()
# no need to provide dirrectory path
# dirrectly give only name of the file
# and extension

In [43]:
# dataframe=df2
df2.to_csv('Data.csv')
df2.to_excel('Data.xlsx')

**Step-11**
**How to read a dataframe**

In [36]:
import pandas as pd 
pd.read_csv('Data.csv')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

In [37]:
import os
os.getcwd()

'C:\\Users\\HP\\Documents\\nareshIT\\EDA'

In [38]:
import pandas as pd 
pd.read_excel('Data.xlsx')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

**step12**

**How to avaid index column**

- while we save the dataframe

- automtiticaly a new column will create

- that we need to avaid

- permission denied means close the data file from laptop

In [49]:
# Dataframe name:df2
# Save the data with out index column
df2.to_csv('Data.csv',index=False)
df2.to_excel('Data.xlsx',index=False)

In [39]:
# read the file
import pandas as pd   
pd.read_csv('Data.csv')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9